CREATE TABLE USERS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	E_MAIL VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	NAME VARCHAR(128) NOT NULL,
	SURNAME VARCHAR(128) NOT NULL,
	GENDER VARCHAR(1) NOT NULL,
	BIRTH DATE NOT NULL	
);

CREATE TABLE EVENTS(
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(128) NOT NULL,
	MANAGER INT NOT NULL,
	DESCRIPTION VARCHAR(1024) NOT NULL,
	DATE TIMESTAMP NOT NULL,
	PICTURE TEXT NOT NULL,
	VISITORS_COUNT INT,
	VISITORS_AGE INT, 
	VISITORS_GENDER VARCHAR(1),
	CONSTRAINT FK_MANAGER_EVENT FOREIGN KEY (MANAGER) REFERENCES USERS (ID) 
);

CREATE TABLE VISITS (
	ID_USER INT NOT NULL,
	ID_EVENT INT NOT NULL,
	CONSTRAINT VISITS_PK PRIMARY KEY (ID_USER, ID_EVENT),
	CONSTRAINT FK_VISITS_USER_FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
	CONSTRAINT FK_VISITS_EVENT FOREIGN KEY (ID_EVENT) REFERENCES EVENTS (ID)
);

CREATE TABLE ADMINS (
	ID INT NOT NULL,
	CONSTRAINT ADMINS_PK PRIMARY KEY (ID),
	CONSTRAINT FK_ADMINS_USERS FOREIGN KEY (ID) REFERENCES USERS (ID)
);

CREATE TABLE SYSTEM_LOG (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ID_EVENT VARCHAR(128) NOT NULL,
	DESCRIPTION VARCHAR(1024) NOT NULL,
	OTHER VARCHAR(1024) NOT NULL
);

CREATE TABLE LOG_USER (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 	
	ID_LOG INT NOT NULL,
	ID_USER INT NOT NULL,
	Date TIMESTAMP NOT NULL,
	CONSTRAINT FK_LOG_SYS FOREIGN KEY (ID_LOG) REFERENCES SYSTEM_LOG (ID),
	CONSTRAINT FK_LOG_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID)	
);
