CREATE TABLE Users (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"E-mail" VARCHAR(128) NOT NULL,
	Password VARCHAR(64) NOT NULL,
	Name VARCHAR(128) NOT NULL,
	Surname VARCHAR(128) NOT NULL,
	Gender VARCHAR(1) NOT NULL,
	Birth DATE NOT NULL	
);

CREATE TABLE Events (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Name VARCHAR(128) NOT NULL,
	Manager INT NOT NULL,
	Description VARCHAR(1024) NOT NULL,
	Date TIMESTAMP NOT NULL,
	Picture TEXT NOT NULL,
	Visitors_count INT,
	Visitors_age INT, 
	Visitors_gender VARCHAR(1),
	CONSTRAINT fk_manager_event FOREIGN KEY (Manager) REFERENCES Users (ID) 
);

CREATE TABLE Visits (
	ID_user INT NOT NULL,
	ID_event INT NOT NULL,
	CONSTRAINT visits_pk PRIMARY KEY (ID_user, ID_event),
	CONSTRAINT fk_visits_user FOREIGN KEY (ID_user) REFERENCES Users (ID),
	CONSTRAINT fk_visits_event FOREIGN KEY (ID_event) REFERENCES Events (ID)
);

CREATE TABLE Admins (
	ID INT NOT NULL,
	CONSTRAINT admins_pk PRIMARY KEY (ID),
	CONSTRAINT fk_admins_users FOREIGN KEY (ID) REFERENCES Users (ID)
);

CREATE TABLE System_log (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	EventID VARCHAR(128) NOT NULL,
	Description VARCHAR(1024) NOT NULL,
	Other VARCHAR(1024) NOT NULL
);

CREATE TABLE Log_user (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 	
	ID_log INT NOT NULL,
	ID_user INT NOT NULL,
	Date TIMESTAMP NOT NULL,
	CONSTRAINT fk_log_sys FOREIGN KEY (ID_log) REFERENCES System_log (ID),
	CONSTRAINT fk_log_user FOREIGN KEY (ID_user) REFERENCES Users (ID)	
);
